version: '3.8'

services:
    nginx:
        image: nginx:latest
        container_name: burning_heroes_nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - fastapi_backend
        restart: always

    db:
        container_name: burning_heroes_db
        image: postgres
        restart: always
        env_file:
            - .database_env
        volumes:
            - burning_heroes_db_data:/var/lib/postgresql/data
        ports:
            - "5432"

    fastapi_backend:
        container_name: burning_heroes_fastapi
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - "8000"
        depends_on:
            - db

volumes:
    burning_heroes_db_data:
