"""empty message

Revision ID: 5037e5305d66
Revises: 06c9fc55e884
Create Date: 2024-03-31 00:05:41.840666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5037e5305d66'
down_revision: Union[str, None] = '06c9fc55e884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('test_questions_test_id_fkey', 'test_questions', type_='foreignkey')
    op.create_foreign_key(None, 'test_questions', 'tests', ['test_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('test_response_options_question_id_fkey', 'test_response_options', type_='foreignkey')
    op.create_foreign_key(None, 'test_response_options', 'test_questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.add_column('tests', sa.Column('user_creator_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'tests', 'users', ['user_creator_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.drop_column('tests', 'user_creator_id')
    op.drop_constraint(None, 'test_response_options', type_='foreignkey')
    op.create_foreign_key('test_response_options_question_id_fkey', 'test_response_options', 'test_questions', ['question_id'], ['id'])
    op.drop_constraint(None, 'test_questions', type_='foreignkey')
    op.create_foreign_key('test_questions_test_id_fkey', 'test_questions', 'tests', ['test_id'], ['id'])
    # ### end Alembic commands ###
